### ISSUE TITLE
百合线中间崩溃

### ISSUE THREAD

**Issue by uetcis** [crskycode/Sakuranouta#1]
![CleanShot 2021-05-09 at 07 51 39@2x](https://user-images.githubusercontent.com/25654046/117556444-bea78080-b09b-11eb-80e9-421500679e25.png)

```
Thread [ 1 ] , Program [ scrgrp4._bp ] , IP [ $00000D50 ] , Instruction [ $905C ] , SP [ $000015F8 ]

( ipl._bp - $00000A69 )
( title._bp - $0000002C )
( title._bp - $0000067F )
( title._bp - $0000074B )
( title._bp - $00000908 )
( scrdrv._bp - $000000E0 )
( scrmain._bp - $0000030C )
( scrgrp4._bp - $000018C1 )
( scrgrp4._bp - $00001391 )

指定されたビットマップ [ 0 , -1 ] のいずれかが無効です
```

环境：wine-5.0

**Comment by crskycode** [comment]
Wine出现的问题与文本无关。

**Comment by wickfw** [comment]
How did you fix the problem?

**Comment by gnpsgwps** [comment]
https://mega.nz/file/ihFCFZJa#jbTfEC2tizi4MX20bJ0mxHzAhKwk7uHZe1tDF3990e8

**Comment by gnpsgwps** [comment]
How did you solve it in the end?

**Comment by wickfw** [comment]
> How did you solve it in the end?

You have to make sure UTF-8 is on in the Unicode Settings for control panel and make sure you Unicode  is Japanese too

**Comment by gnpsgwps** [comment]
But mine is the Chinese version.

**Comment by gnpsgwps** [comment]
I tried it but the game can't be opened.
