### ISSUE TITLE
About the font

### ISSUE THREAD

**Issue by Sisulizer** [crskycode/Sakuranouta#2]
My friend is going to translate this vn and our language has special characters like à á ì í, 134 in total. He had to used special font for replacing them. At first the game showed no error like this:
![image](https://user-images.githubusercontent.com/91543117/140877530-d0ee247a-c137-49fc-b650-50795a5276b3.png)
But when he saved and loaded it became like this: 
![image](https://user-images.githubusercontent.com/91543117/140877636-2d2f503e-54c8-46d5-8a92-1140b54dc863.png)
It supposed to be "Người" but the game showed "Ngư ờ i" and other words to. The problem I found was using hiragana and katakana character caused this. Do you have any idea how to fix? It will be easier if the game can set the character range to utf8 so that he doesn't have to use font

**Comment by crskycode** [comment]
This game uses an old version of the BGI engine. It only supports Shift_JIS code page. If you need to extend the code page to support more characters, you need to Hack the engine. There is no way to make the engine support UTF-8 code page.
More information https://github.com/crskycode/Sakuranouta/blob/main/BGI.txt

**Comment by Sisulizer** [comment]
Then what about the font 
Normal: 
![image](https://user-images.githubusercontent.com/91543117/141048226-ba74d2ca-04fa-4bea-8e7c-e18bc9a265ee.png)
When I load:
![image](https://user-images.githubusercontent.com/91543117/141048243-9ec4bd99-0a9c-49ee-a45c-13e7ea7e6e3f.png)
Here's what I put in the script:
![image](https://user-images.githubusercontent.com/91543117/141048272-a1ad718e-33c6-44e8-b95d-e7ed46bdb7f2.png)
