### ISSUE TITLE
sakura no uta error

### ISSUE THREAD

**Issue by bingleboggle12** [crskycode/Sakuranouta#3]
Thread [ 1 ] , Program [ scrdrv._bp ] , IP [ $00000726 ] , Instruction [ $79 ] , SP [ $00001468 ]

( ipl._bp - $00000A69 )
( title._bp - $0000002C )
( title._bp - $0000067F )
( title._bp - $0000074B )
( title._bp - $00000908 )
( scrdrv._bp - $000000E0 )
( scrmain._bp - $0000030C )

未定義の命令コード[$0336] が検出されました

ran using japanese locale emulator admin

![Capturesakuuta](https://github.com/crskycode/Sakuranouta/assets/136190906/c3df6e36-6761-423a-833f-d2a2acae8c00)

**Comment by crskycode** [comment]
Try remove the message lines here. Rebuild the script again.

**Comment by bingleboggle12** [comment]
sorry im not sure what you mean. how do i remove message lines / rebuild the script? i apologize im not very good with computers

**Comment by Cosetto** [comment]
https://forums.fuwanovel.net/topic/26467-sakura-no-uta-english-translation-patch-problem/#comment-538585
fix patch in the thread
